export default {
  UNDEFINED: 'UNDEFINED',
  WAITING_FOR_PLAYER: 'WAITING_FOR_PLAYER',
  WAITING_ON_INVITATION_RESPONSE: 'WAITING_ON_INVITATION_RESPONSE',
  RECEIVED_INVITATION: 'RECEIVED_INVITATION',
  NEW_GAME_STARTED: 'NEW_GAME_STARTED',
  PLAYING: 'PLAYING'
}
